package org.graphiks.kanvas.pipeline

enum class PrimitiveTopology { TRIANGLE_LIST, TRIANGLE_STRIP, LINE_STRIP, LINE_LIST, POINT_LIST }
enum class BlendFactor {
    ZERO, ONE, SRC_COLOR, ONE_MINUS_SRC_COLOR, DST_COLOR, ONE_MINUS_DST_COLOR,
    SRC_ALPHA, ONE_MINUS_SRC_ALPHA, DST_ALPHA, ONE_MINUS_DST_ALPHA,
    CONSTANT_COLOR, ONE_MINUS_CONSTANT_COLOR, CONSTANT_ALPHA, ONE_MINUS_CONSTANT_ALPHA,
    SRC_ALPHA_SATURATED,
}
enum class BlendOp { ADD, SUBTRACT, REVERSE_SUBTRACT, MIN, MAX }
enum class CompareOp { NEVER, LESS, EQUAL, LESS_EQUAL, GREATER, NOT_EQUAL, GREATER_EQUAL, ALWAYS }
enum class StencilOp { KEEP, ZERO, REPLACE, INVERT, INCREMENT_CLAMP, DECREMENT_CLAMP, INCREMENT_WRAP, DECREMENT_WRAP }
enum class VertexFormat { FLOAT32, FLOAT32x2, FLOAT32x3, FLOAT32x4, UINT8x4, SINT16x2, SINT16x4 }
enum class VertexStepMode { VERTEX, INSTANCE }
enum class LoadOp { CLEAR, LOAD }
enum class StoreOp { STORE, DISCARD }
enum class UniformType { FLOAT, FLOAT2, FLOAT3, FLOAT4, MAT3X3, MAT4X4 }
enum class ChildType { SHADER, COLOR_FILTER, BLENDER }
