package org.graphiks.kanvas.gpu.renderer.passes

/** Canonical identity-only set of the 29 supported Skia-compatible blend modes. */
enum class GPUBlendMode(val gpuLabel: String) {
    CLEAR("clear"),
    SRC_OVER("src_over"),
    SRC("src"),
    DST("dst"),
    DST_OVER("dst_over"),
    SRC_IN("src_in"),
    DST_IN("dst_in"),
    SRC_OUT("src_out"),
    DST_OUT("dst_out"),
    SRC_ATOP("src_atop"),
    DST_ATOP("dst_atop"),
    XOR("xor"),
    PLUS("plus"),
    MODULATE("modulate"),
    MULTIPLY("multiply"),
    SCREEN("screen"),
    OVERLAY("overlay"),
    DARKEN("darken"),
    LIGHTEN("lighten"),
    COLOR_DODGE("color_dodge"),
    COLOR_BURN("color_burn"),
    HARD_LIGHT("hard_light"),
    SOFT_LIGHT("soft_light"),
    DIFFERENCE("difference"),
    EXCLUSION("exclusion"),
    HUE("hue"),
    SATURATION("saturation"),
    COLOR("color"),
    LUMINOSITY("luminosity"),
}
