package org.graphiks.kanvas.text

import org.graphiks.kanvas.geometry.Path
import org.graphiks.kanvas.geometry.PathCommand
import org.graphiks.kanvas.paint.Paint
import org.graphiks.kanvas.types.Color
import org.graphiks.math.geometry.Point2F32
import org.graphiks.math.vector.Vector2F32
import java.util.Base64
import kotlin.test.Test
import kotlin.test.assertContentEquals
import kotlin.test.assertEquals
import kotlin.test.assertIs
import kotlin.test.assertNotNull

class CustomTypefaceTest {
    @Test
    fun `legacy glyph path data keeps its wire shape across semantic migration`() {
        val legacy = Base64.getDecoder().decode(LEGACY_PATH_TYPEFACE_DATA)

        val decoded = CustomTypeface.deserialize(legacy)
        val path = requireNotNull(decoded.getGlyphPath('A'.code, 1f))
        assertEquals(
            listOf(
                PathCommand.Move(Point2F32(1f, 2f)),
                PathCommand.Line(Point2F32(3f, 4f)),
                PathCommand.Quad(Point2F32(5f, 6f), Point2F32(7f, 8f)),
                PathCommand.Cubic(Point2F32(9f, 10f), Point2F32(11f, 12f), Point2F32(13f, 14f)),
                PathCommand.ArcTo(
                    Vector2F32(15f, 16f),
                    17f,
                    largeArc = true,
                    sweep = false,
                    endpoint = Point2F32(18f, 19f),
                ),
                PathCommand.Close,
            ),
            path.commands(),
        )
        assertContentEquals(legacy, decoded.serialize())
    }

    @Test
    fun `custom typeface preserves direct and drawable glyphs across serialization`() {
        val direct = Path().addRect(org.graphiks.kanvas.types.Rect.fromXYWH(0f, 0f, 0.5f, 1f))
        val drawable = Path().addCircle(0.5f, 0.5f, 0.5f)
        val typeface = CustomTypeface.Builder("test-user-typeface")
            .setMetrics(FontMetrics(ascent = 0.8f, descent = -0.2f, leading = 0.1f))
            .setGlyph('A'.code, advance = 0.6f, path = direct)
            .setDrawableGlyph('B'.code, advance = 0.7f, path = drawable, paint = Paint.fill(Color.fromArgb(255, 0, 128, 0)))
            .build()

        val decoded = CustomTypeface.deserialize(typeface.serialize())

        assertEquals('A'.code, decoded.glyphIdForCodepoint('A'.code))
        assertEquals(12f, decoded.getAdvance('A'.code, 20f))
        assertNotNull(decoded.getGlyphPath('B'.code, 20f))
        assertEquals(16f, decoded.getMetrics(20f)?.ascent)
        val painted = assertIs<GlyphPaintProvider>(decoded).paintForGlyph('B'.code)
        assertEquals(Color.fromArgb(255, 0, 128, 0), painted?.color)
    }
}

// Generated by origin/master (39fa5cf30) before Point2F32/Vector2F32 migration.
private const val LEGACY_PATH_TYPEFACE_DATA =
    "S1RGMQALbGVnYWN5LXBhdGg/TMzNvkzMzQAAAAAAAAAAAAAAAAAAAAEAAABBQaAAAAAAAAAAAAAABgABAgMEBQAAAAs/gAAAQAAAAEBAAABAgAAAQKAAAEDAAABA4AAAQQAAAEEQAABBIAAAQTAAAEFAAABBUAAAQWAAAEFwAABBgAAAQYgAAD+AAAAAAAAAAAAAAEGQAABBmAAA"
