package org.graphiks.kanvas.gpu.renderer.scenes.offscreen

import org.graphiks.kanvas.gpu.renderer.scenes.catalog.GPURendererSceneRegistry
import java.io.File
import javax.imageio.ImageIO
import kotlin.test.Test
import kotlin.test.assertTrue

/**
 * Compares the external Cairo reference PNGs (generated by
 * tools/cairo-reference/render_scene) against the committed GPU offscreen
 * render.png for each scene that has both assets.
 *
 * Cairo is a completely independent renderer (no shared code with the GPU
 * pipeline), so it serves as a ground-truth reference for FillRect, Clip,
 * SaveLayer, and alpha-blending operations. Shape-level differences
 * (FillRRect anti-aliasing, gradient interpolation) are expected and are
 * tracked here as diagnostic evidence rather than hard pass/fail gates.
 */
class CairoReferenceParityTest {

    private data class ParityDiff(val total: Int, val mismatch: Int, val maxDelta: Int, val similarity: Double) {
        override fun toString(): String =
            "ParityDiff(similarity=${"%.4f".format(similarity)}, mismatch=$mismatch/$total, maxChannelDelta=$maxDelta)"
    }

    private val cairoBase: File by lazy {
        File(repoRoot(), "tools/cairo-reference/out")
    }

    private val gpuBase: File by lazy {
        File(repoRoot(), "reports/gpu-renderer-scenes/offscreen")
    }

    @Test
    fun cairoReferences_matchGpuRenderWithinTolerance() {
        val results = mutableListOf<Pair<String, ParityDiff>>()
        val skipped = mutableListOf<String>()

        for (scene in GPURendererSceneRegistry.scenes) {
            val id = scene.sceneId.value
            val cairoFile = File(cairoBase, "$id.png")
            val gpuFile = File(gpuBase, id, "render.png")

            if (!cairoFile.isFile || !gpuFile.isFile) {
                if (!cairoFile.isFile) skipped.add("$id (no Cairo ref)")
                if (!gpuFile.isFile) skipped.add("$id (no GPU render.png)")
                continue
            }

            val cairo = loadPng(cairoFile)
            val gpu = loadPng(gpuFile)
            val d = diff(cairo, gpu, tolerance = 8)
            results.add(id to d)
            println("[cairo-parity] $id -> $d")
        }

        println()
        println("=== Cairo Reference Parity Summary ===")
        println("Scenes compared: ${results.size}")
        println()

        for ((id, d) in results.sortedBy { it.second.similarity }) {
            val status = if (d.similarity >= 0.99) "PASS" else "DIFF"
            println("  $status $id similarity=${"%.4f".format(d.similarity)} mismatch=${d.mismatch}/${d.total} maxDelta=${d.maxDelta}")
        }

        if (skipped.isNotEmpty()) {
            println()
            println("Skipped (no reference PNGs):")
            for (s in skipped.sorted()) println("  - $s")
        }

        // At minimum the simple fill-rect scenes must match perfectly
        val failResults = results.filter { it.second.similarity < 0.99 }
        assertTrue(
            failResults.isEmpty(),
            buildString {
                appendLine("${failResults.size} scene(s) below 0.99 similarity threshold:")
                for ((id, d) in failResults) {
                    appendLine("  $id: $d")
                    appendLine("    Known differences: shape AA or gradient interpolation")
                }
            },
        )
    }

    private fun diff(a: RefImage, b: RefImage, tolerance: Int): ParityDiff {
        require(a.width == b.width && a.height == b.height) {
            "dimension mismatch ${a.width}x${a.height} vs ${b.width}x${b.height}"
        }
        val total = a.width * a.height
        var mismatch = 0
        var maxDelta = 0
        var i = 0
        while (i < a.rgba.size) {
            val dr = kotlin.math.abs((a.rgba[i].toInt() and 0xFF) - (b.rgba[i].toInt() and 0xFF))
            val dg = kotlin.math.abs((a.rgba[i + 1].toInt() and 0xFF) - (b.rgba[i + 1].toInt() and 0xFF))
            val db = kotlin.math.abs((a.rgba[i + 2].toInt() and 0xFF) - (b.rgba[i + 2].toInt() and 0xFF))
            val m = maxOf(dr, dg, db)
            if (m > maxDelta) maxDelta = m
            if (m > tolerance) mismatch++
            i += 4
        }
        return ParityDiff(total, mismatch, maxDelta, (total - mismatch).toDouble() / total)
    }

    private fun loadPng(file: File): RefImage {
        val img = ImageIO.read(file) ?: error("ImageIO failed to read $file")
        val w = img.width
        val h = img.height
        val rgba = ByteArray(w * h * 4)
        for (y in 0 until h) {
            for (x in 0 until w) {
                val argb = img.getRGB(x, y)
                val base = (y * w + x) * 4
                rgba[base] = ((argb shr 16) and 0xFF).toByte()
                rgba[base + 1] = ((argb shr 8) and 0xFF).toByte()
                rgba[base + 2] = (argb and 0xFF).toByte()
                rgba[base + 3] = ((argb ushr 24) and 0xFF).toByte()
            }
        }
        return RefImage(w, h, rgba)
    }

    private fun repoRoot(): File {
        var dir: File? = File(System.getProperty("user.dir")).absoluteFile
        while (dir != null) {
            if (File(dir, "reports/gpu-renderer-scenes/offscreen").isDirectory) return dir
            dir = dir.parentFile
        }
        error("Could not locate repo root from ${System.getProperty("user.dir")}")
    }
}
