package org.skia.gpu.webgpu.tools

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test
import java.nio.file.Files
import java.nio.file.Path

class GeneratedSolidRectWgslTest {
    private val goldenPath: Path = Path.of("src/test/resources/wgsl-generated/solid_rect_generated.wgsl")

    @Test
    fun `generated solid rect wgsl is deterministic`() {
        val first = GeneratedSolidRectWgsl.generateDeterministic()
        val second = GeneratedSolidRectWgsl.generateDeterministic()
        assertEquals(first, second)
        assertTrue(first.contains("Generated by WebGPU-KTypes WGSL Backend"))
    }

    @Test
    fun `generated solid rect wgsl matches expected text`() {
        val generated = GeneratedSolidRectWgsl.generateDeterministic().replace("\r\n", "\n")
        if (System.getenv("UPDATE_WGSL_GOLDEN") == "true") {
            Files.createDirectories(goldenPath.parent)
            Files.writeString(goldenPath, generated)
        }
        val expected = Files.readString(goldenPath).replace("\r\n", "\n")
        assertEquals(expected, generated)
    }

    @Test
    fun `generated solid rect wgsl parses with parser`() {
        val source = GeneratedSolidRectWgsl.generateDeterministic()
        val validation = GeneratedSolidRectWgsl.validate(source)
        assertTrue(validation.isSuccess, "expected generated WGSL to parse: ${validation.diagnostics}")
    }
}
