package org.skia.gpu.webgpu.tools

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.io.TempDir
import java.nio.file.Files
import java.nio.file.Path

class GeneratedLinearGradientWgslTest {
    private val goldenPath: Path = Path.of("src/test/resources/wgsl-generated/linear_gradient_generated.wgsl")

    @Test
    fun `generated linear gradient wgsl is deterministic`() {
        val first = GeneratedLinearGradientWgsl.generateDeterministic()
        val second = GeneratedLinearGradientWgsl.generateDeterministic()
        assertEquals(first, second)
        assertTrue(first.contains("Generated by Kanvas WGSL pipeline generator"))
    }

    @Test
    fun `generated linear gradient wgsl matches expected text`() {
        val generated = GeneratedLinearGradientWgsl.generateDeterministic().replace("\r\n", "\n")
        if (System.getenv("UPDATE_WGSL_GOLDEN") == "true") {
            Files.createDirectories(goldenPath.parent)
            Files.writeString(goldenPath, generated)
        }
        val expected = Files.readString(goldenPath).replace("\r\n", "\n")
        assertEquals(expected, generated)
    }

    @Test
    fun `generated linear gradient wgsl parses with parser`() {
        val source = GeneratedLinearGradientWgsl.generateDeterministic()
        val validation = GeneratedLinearGradientWgsl.validate(source)
        assertTrue(validation.isSuccess, "expected generated WGSL to parse: ${validation.diagnostics}")
    }

    @Test
    fun `generated linear gradient uniform layout is reflected`(@TempDir tempDir: Path) {
        Files.writeString(tempDir.resolve("linear_gradient_generated.wgsl"), GeneratedLinearGradientWgsl.generateDeterministic())
        val report = WgslValidationReport.run(tempDir).files.single()
        assertTrue(report.success, "expected generated WGSL to parse: ${report.diagnostics}")
        assertTrue(report.entryPoints.contains("vertex:vs_main"))
        assertTrue(report.entryPoints.contains("fragment:fs_clamp"))
        assertTrue(report.bindings.any { it == "uniforms@group=0,binding=0" })

        val uniforms = report.uniformStructs.single { it.variable == "uniforms" }
        val offsets = uniforms.members.associate { it.name to it.offset }
        assertEquals(0, offsets["startEnd"])
        assertEquals(16, offsets["viewport"])
        assertEquals(32, offsets["countPad"])
        assertEquals(48, offsets["positions"])
        assertEquals(304, offsets["colors"])
        assertEquals(560, offsets["clipShapeBounds"])
        assertEquals(576, offsets["clipShapeRadiiKind"])
        assertEquals(592, offsets["colorFilterKindMode"])
        assertEquals(672, offsets["colorFilterBias"])
    }
}
