package org.skia.pathops

import com.fasterxml.jackson.databind.ObjectMapper
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test
import org.junit.jupiter.params.ParameterizedTest
import org.junit.jupiter.params.provider.MethodSource
import org.skia.foundation.SkPath
import org.skia.foundation.SkPathBuilder
import org.skia.foundation.SkPathFillType
import java.util.stream.Stream

/**
 * D1.4 — PathOps regression harvest.
 *
 * Drives the upstream Skia
 * [`tests/PathOpsOpTest.cpp`](https://github.com/google/skia/blob/main/tests/PathOpsOpTest.cpp)
 * fixtures through our [SkPathOps.Op] entry point, asserting only that
 * **no fixture crashes the engine and every fixture produces a finite
 * [SkPath] result**. Pixel-similarity vs upstream is *not* checked at
 * this level — that would require a separate rasteriser harness against
 * upstream PNG references.
 *
 * **Why "no crash" alone is valuable** — the upstream test suite
 * includes ~50 fuzz / crbug / bug regressions ; running them through
 * our port immediately surfaces any latent NPE / infinite-loop /
 * stack-overflow / div-by-zero that internal-component tests miss.
 * Pixel parity can be ratcheted in a follow-up slice.
 *
 * **Source of fixtures** : `kanvas-skia/src/test/resources/pathops/op_fixtures.json`,
 * generated by `kanvas-skia/tools/extract_pathops_fixtures.py` from
 * the upstream `.cpp`. Re-run the script when upstream gains new
 * fixtures.
 *
 * **Schema** (per fixture) :
 * ```json
 * {
 *   "name": "cubicOp1d",
 *   "fillTypeA": "kWinding",   // kWinding | kEvenOdd | kInverse{Winding,EvenOdd}
 *   "fillTypeB": "kWinding",
 *   "pathA":    [["moveTo", 0, 1], ["cubicTo", 0, 2, 1, 0, 1, 0], ["close"]],
 *   "pathB":    [["moveTo", 0, 1], ["cubicTo", 0, 1, 1, 0, 2, 0], ["close"]],
 *   "op":       "kDifference"   // kDifference | kIntersect | kUnion | kXOR | kReverseDifference
 * }
 * ```
 *
 * **Ratchet floor** — the [`pathops Op upstream-fixture survives the engine`]
 * parameterised test counts pass / fail / null-result / exception
 * outcomes ; the [`pathops Op survival rate stays at-or-above the floor`]
 * smoke test enforces a global minimum survival rate. Bumping the
 * floor as the engine improves is how we ratchet — never lower it
 * unintentionally.
 */
class PathOpsRegressionRunner {

    /**
     * Stream every parsed fixture through [SkPathOps.Op] and assert
     * the result is non-null + finite. Failures are recorded but do
     * **not** fail the build individually — the global floor is
     * enforced by [`pathops Op survival rate stays at-or-above the floor`].
     * Treating each fixture as soft-fail keeps the test suite usable
     * during ratcheting (no avalanche of red).
     */
    @ParameterizedTest(name = "{0}")
    @MethodSource("upstreamFixtures")
    fun `pathops Op upstream-fixture survives the engine`(fixture: PathOpsFixture) {
        // Soft assertion — record outcome in the shared counter ;
        // never fail the parameterised test directly. The global
        // floor test is the gate.
        val outcome = runFixture(fixture)
        outcomes[fixture.name] = outcome
    }

    /**
     * Smoke test — enforce a survival-rate floor across the full
     * fixture corpus. Every JUnit run replays
     * [pathops Op upstream-fixture survives the engine] before this
     * test and accumulates outcomes ; we then check the rate.
     *
     * **Floor calibration** — the floor is set conservatively below
     * the current measured rate so future improvements ratchet up
     * the value rather than be silently undone. Any drop below the
     * floor blocks the build ; the maintainer must either fix the
     * regression or **lower the floor with a test commit** that
     * explains why.
     */
    @Test
    fun `pathops Op survival rate stays at-or-above the floor`() {
        // Run every fixture through the engine if the parameterised
        // test hasn't already done so (e.g. when this test is run
        // in isolation via `--tests`).
        val fixtures = upstreamFixtures().toList()
        if (outcomes.size < fixtures.size) {
            for (f in fixtures) {
                outcomes.putIfAbsent(f.name, runFixture(f))
            }
        }
        val total = outcomes.size
        val survived = outcomes.values.count { it == Outcome.SURVIVED }
        val rate = if (total == 0) 0.0 else survived.toDouble() / total
        // Initial floor — bumped as the engine improves. See
        // PathOpsRegressionRunner.kdoc for the ratcheting policy.
        val floor = INITIAL_SURVIVAL_FLOOR
        // One-line rate breakdown — gives maintainers running with
        // `--info` instant visibility into the ratchet's distance to
        // the floor without re-grepping the test report XML.
        val byOutcome = outcomes.values.groupingBy { it }.eachCount()
        println(
            "[PathOpsRegression] $survived / $total survived " +
                "(${"%.2f".format(rate * 100)} %) ; " +
                "floor = ${"%.2f".format(floor * 100)} % ; " +
                "outcomes = $byOutcome",
        )
        assertTrue(
            rate >= floor,
            buildString {
                appendLine("Survival rate $rate ($survived / $total) < floor $floor")
                appendLine("Failing fixtures :")
                outcomes.entries
                    .filter { it.value != Outcome.SURVIVED }
                    .sortedBy { it.key }
                    .take(20)
                    .forEach { appendLine("  ${it.key} : ${it.value}") }
                if (outcomes.values.count { it != Outcome.SURVIVED } > 20) {
                    appendLine("  ... (${outcomes.values.count { it != Outcome.SURVIVED } - 20} more)")
                }
            },
        )
    }

    /**
     * Pixel-parity smoke test — orthogonal to the survival floor.
     * Every SURVIVED fixture has its result compared, pixel-wise,
     * against an independent oracle (see [PathOpsPixelOracle]). The
     * fraction of SURVIVED fixtures whose engine result also matches
     * the oracle is gated by [INITIAL_PIXEL_FLOOR].
     *
     * **Floor calibration** : the same monotonic-bump rule applies as
     * the survival floor — bump as the engine improves, never lower
     * without a maintainer comment justifying the regression.
     *
     * **Why orthogonal** : a fixture can survive (no crash, finite
     * result) yet still rasterise to a different shape than the
     * oracle. The two metrics together give a more honest picture
     * than either alone — survival catches engine crashes, parity
     * catches algorithmic bugs.
     */
    @Test
    fun `pathops Op pixel-parity rate stays at-or-above the floor`() {
        val fixtures = upstreamFixtures().toList()
        if (outcomes.size < fixtures.size) {
            for (f in fixtures) {
                outcomes.putIfAbsent(f.name, runFixture(f))
            }
        }
        // Only count fixtures where the engine produced a SURVIVED
        // result — otherwise there's no path to pixel-compare.
        val candidates = pixelOutcomes.size
        val matches = pixelOutcomes.values.count {
            it == PathOpsPixelOracle.PixelOutcome.PIXEL_MATCH ||
                it == PathOpsPixelOracle.PixelOutcome.DEGENERATE
        }
        val rate = if (candidates == 0) 0.0 else matches.toDouble() / candidates
        val floor = INITIAL_PIXEL_FLOOR
        val byOutcome = pixelOutcomes.values.groupingBy { it }.eachCount()
        println(
            "[PathOpsRegression] $matches / $candidates pixel-match " +
                "(${"%.2f".format(rate * 100)} %) ; " +
                "floor = ${"%.2f".format(floor * 100)} % ; " +
                "outcomes = $byOutcome",
        )
        assertTrue(
            rate >= floor,
            buildString {
                appendLine("Pixel-parity rate $rate ($matches / $candidates) < floor $floor")
                appendLine("Diverging fixtures :")
                pixelOutcomes.entries
                    .filter { it.value == PathOpsPixelOracle.PixelOutcome.PIXEL_DIVERGE }
                    .sortedBy { it.key }
                    .take(20)
                    .forEach { appendLine("  ${it.key}") }
                val divergeCount = pixelOutcomes.values.count {
                    it == PathOpsPixelOracle.PixelOutcome.PIXEL_DIVERGE
                }
                if (divergeCount > 20) {
                    appendLine("  ... (${divergeCount - 20} more)")
                }
            },
        )
    }

    // ─── Engine driver ────────────────────────────────────────────────

    private fun runFixture(f: PathOpsFixture): Outcome {
        val pathA = try {
            buildPath(f.fillTypeA, f.pathA)
        } catch (t: Throwable) {
            return Outcome.BUILD_FAILED
        }
        val pathB = try {
            buildPath(f.fillTypeB, f.pathB)
        } catch (t: Throwable) {
            return Outcome.BUILD_FAILED
        }
        val op = parseOp(f.op) ?: return Outcome.UNKNOWN_OP
        val result = try {
            SkPathOps.Op(pathA, pathB, op)
        } catch (t: Throwable) {
            return Outcome.THREW
        }
        if (result == null) return Outcome.RETURNED_NULL
        // Verify all coords are finite — catches degenerate output.
        if (!result.isFinite()) return Outcome.NON_FINITE
        // Pixel parity vs the independent oracle — see
        // [PathOpsPixelOracle] for the algorithm. Only meaningful on a
        // SURVIVED engine result ; we cache the outcome on
        // [pixelOutcomes] for the parallel pixel-parity floor test.
        try {
            pixelOutcomes[f.name] = PathOpsPixelOracle.compare(pathA, pathB, op, result)
        } catch (t: Throwable) {
            // The oracle itself can throw on degenerate scaling
            // (e.g. paths reduced to a single point under the oracle's
            // matrix). Bucket as DEGENERATE — caller will see it as
            // "no parity verdict" rather than a fail.
            pixelOutcomes[f.name] = PathOpsPixelOracle.PixelOutcome.DEGENERATE
        }
        return Outcome.SURVIVED
    }

    /** Apply a verb stream to a fresh [SkPathBuilder]. */
    private fun buildPath(fillTypeName: String, verbs: List<List<Any?>>): SkPath {
        val fillType = parseFillType(fillTypeName)
        val builder = SkPathBuilder().apply { setFillType(fillType) }
        for (v in verbs) {
            val verb = v[0] as String
            val args = v.drop(1).map { (it as Number).toFloat() }
            applyVerb(builder, verb, args, fillType)
        }
        // Final guard — a reset on the very last verb without a follow-up
        // setFillType could leave the builder on kWinding ; force the
        // recorded fill type so the resulting SkPath matches upstream.
        builder.setFillType(fillType)
        return builder.detach()
    }

    private fun applyVerb(
        builder: SkPathBuilder,
        verb: String,
        args: List<Float>,
        fillType: SkPathFillType,
    ) {
        when (verb) {
            "moveTo" -> {
                require(args.size == 2) { "moveTo expects 2 args" }
                builder.moveTo(args[0], args[1])
            }
            "lineTo" -> {
                require(args.size == 2) { "lineTo expects 2 args" }
                builder.lineTo(args[0], args[1])
            }
            "quadTo" -> {
                require(args.size == 4) { "quadTo expects 4 args" }
                builder.quadTo(args[0], args[1], args[2], args[3])
            }
            "conicTo" -> {
                require(args.size == 5) { "conicTo expects 5 args" }
                builder.conicTo(args[0], args[1], args[2], args[3], args[4])
            }
            "cubicTo" -> {
                require(args.size == 6) { "cubicTo expects 6 args" }
                builder.cubicTo(args[0], args[1], args[2], args[3], args[4], args[5])
            }
            "close" -> builder.close()
            "reset" -> {
                // Upstream `path.reset()` clears verbs / weights and
                // resets fill type to kWinding. We mirror with
                // [SkPathBuilder.reset] then re-apply the JSON's
                // recorded fillType so the post-reset state matches.
                builder.reset()
                builder.setFillType(fillType)
            }
            else -> error("unknown verb: $verb")
        }
    }

    private fun parseFillType(name: String): SkPathFillType = when (name) {
        "kWinding" -> SkPathFillType.kWinding
        "kEvenOdd" -> SkPathFillType.kEvenOdd
        "kInverseWinding" -> SkPathFillType.kInverseWinding
        "kInverseEvenOdd" -> SkPathFillType.kInverseEvenOdd
        else -> error("unknown fillType: $name")
    }

    private fun parseOp(name: String): SkPathOp? = when (name) {
        "kDifference" -> SkPathOp.kDifference
        "kIntersect" -> SkPathOp.kIntersect
        "kUnion" -> SkPathOp.kUnion
        "kXOR" -> SkPathOp.kXOR
        "kReverseDifference" -> SkPathOp.kReverseDifference
        else -> null
    }

    // ─── Outcome accounting ───────────────────────────────────────────

    /** What happened to a fixture when run through the engine. */
    private enum class Outcome {
        /** Engine returned a non-null finite SkPath — happy path. */
        SURVIVED,
        /** Engine returned `null` — Op declined (degenerate / failed). */
        RETURNED_NULL,
        /** Engine returned a SkPath with a non-finite coord. */
        NON_FINITE,
        /** Engine threw — NPE / infinite loop hit a guard / crash. */
        THREW,
        /** Builder rejected the fixture's verb stream. */
        BUILD_FAILED,
        /** Fixture op string didn't map to a known SkPathOp. */
        UNKNOWN_OP,
    }

    public data class PathOpsFixture(
        val name: String,
        val fillTypeA: String,
        val fillTypeB: String,
        val pathA: List<List<Any?>>,
        val pathB: List<List<Any?>>,
        val op: String,
    ) {
        // JUnit's `name = "{0}"` calls toString — keep it short so
        // CI logs stay readable.
        override fun toString(): String = name
    }

    public companion object {
        /**
         * Outcome counter shared between the parameterised test and
         * the floor-enforcement test. JUnit guarantees the
         * parameterised method runs before any plain `@Test` in a
         * single test-class lifecycle, so the floor test sees
         * complete data.
         *
         * Reset on each instance via the no-op nature of `MethodSource`
         * — JUnit re-instantiates the test class once per fixture in
         * default mode, so we use a static counter to aggregate.
         */
        private val outcomes: MutableMap<String, Outcome> = LinkedHashMap()

        /**
         * Pixel-parity outcome per SURVIVED fixture — populated by
         * [runFixture] alongside the survival outcome. Empty until the
         * runner has been driven once. See [PathOpsPixelOracle] for
         * the bucketing semantics.
         */
        private val pixelOutcomes:
            MutableMap<String, PathOpsPixelOracle.PixelOutcome> = LinkedHashMap()

        /**
         * Floor for the survival-rate ratchet. Bump this when the
         * engine improves ; never lower without a maintainer comment
         * justifying the regression.
         *
         * **Calibration history** :
         *  - **D1.4 MVP** (initial run, 303 fixtures) : 293 survived
         *    = 96.7 %. Floor pinned at 90 %.
         *  - **D1.4 extractor coverage follow-up** (+32 fixtures →
         *    335 total) : 323 / 335 = 96.4 %. Floor stays at 90 %.
         *  - **D1.4 RETURNED_NULL debug pass — stale empty-result guard
         *    removed** (no fixture-count change, just an engine fix) :
         *    `SkPathOps.Op` no longer treats `bridgeOp`'s legitimate
         *    empty-writer output as a failure. 11 of the 12 previous
         *    `RETURNED_NULL` fixtures now correctly return the empty
         *    `SkPath` (e.g. `Op(A, A, kDifference) = ∅`). Survival
         *    jumps to **334 / 335 = 99.7 %**. Floor bumped 90 % → 99 %
         *    (0.7 pp cushion). Sole remaining null-return : `cubicOp35d`
         *    (two crossing cubics with sub-pixel intersection — needs
         *    deeper algorithmic debug ; tracked separately).
         *
         * Bump the floor monotonically as future debug passes land.
         */
        private const val INITIAL_SURVIVAL_FLOOR: Double = 0.99

        /**
         * Floor for the pixel-parity ratchet. See
         * `pathops Op pixel-parity rate stays at-or-above the floor`
         * for the semantics. Bumped monotonically as the engine's
         * shape-correctness improves ; the rate is only meaningful
         * over fixtures that SURVIVED (no crash + finite result).
         *
         * **Initial calibration** (post-D1.2.h.10, run sur master au
         * 2026-05-09) : **320 / 334 = 95.8 %** pixel-match against
         * an independent rasteriser-set-op oracle (see
         * [PathOpsPixelOracle]). 14 fixtures diverge — likely a
         * mix of cubic-cubic intersection precision losses and
         * fillType handling on inverse-fill inputs. Floor pinned at
         * **90 %** (~5.8 pp cushion) ; bump as algo debug passes
         * land. cubicOp35d (the sole `RETURNED_NULL`) is excluded
         * from this metric — only SURVIVED fixtures count.
         *
         * **D1.4.a.1** (`testRect1_u` debug pass, run au 2026-05-10) :
         * `SkPathOps.Op` empty-input fast path now calls `Simplify(work)`
         * (previously skipped, on the false hypothesis that work was
         * always already-simple). Recovers `testRect1_u` (3 overlapping
         * winding rect sub-contours OR'd with empty pathB ; the
         * unsimplified result rendered with the new even-odd fill
         * produced holes where winding=2 sub-contour overlaps fell on
         * even pixels). New rate **321 / 334 = 96.11 %** ; PIXEL_DIVERGE
         * count down 14 → 13. Floor bumped 90 % → 95 % (~1.1 pp
         * cushion). `fuzz38`-style fuzzer inputs trip `Simplify` itself
         * — the fast path falls back to the legacy fillType remap when
         * `Simplify` returns null, preserving the survival rate on
         * pathological inputs.
         */
        private const val INITIAL_PIXEL_FLOOR: Double = 0.95

        /**
         * Load fixtures from the JSON resource. Cached lazily so the
         * parameterised test doesn't re-parse on every invocation.
         */
        private val fixtureCache: List<PathOpsFixture> by lazy {
            val mapper = ObjectMapper()
            val stream = PathOpsRegressionRunner::class.java.getResourceAsStream(
                "/pathops/op_fixtures.json"
            ) ?: error(
                "missing resource /pathops/op_fixtures.json — re-run " +
                    "kanvas-skia/tools/extract_pathops_fixtures.py to regenerate"
            )
            val root = mapper.readTree(stream)
            val arr = root.path("fixtures")
            val out = ArrayList<PathOpsFixture>(arr.size())
            for (n in arr) {
                fun verbs(node: com.fasterxml.jackson.databind.JsonNode): List<List<Any?>> {
                    val rows = ArrayList<List<Any?>>(node.size())
                    for (row in node) {
                        val cells = ArrayList<Any?>(row.size())
                        for (c in row) {
                            cells += if (c.isTextual) c.textValue() else c.doubleValue()
                        }
                        rows += cells
                    }
                    return rows
                }
                out += PathOpsFixture(
                    name = n.path("name").asText(),
                    fillTypeA = n.path("fillTypeA").asText(),
                    fillTypeB = n.path("fillTypeB").asText(),
                    pathA = verbs(n.path("pathA")),
                    pathB = verbs(n.path("pathB")),
                    op = n.path("op").asText(),
                )
            }
            out
        }

        @JvmStatic
        public fun upstreamFixtures(): Stream<PathOpsFixture> = fixtureCache.stream()
    }
}
