package org.skia.gpu.webgpu.tools

import org.graphiks.wgsl.parser.parseWgslResult

object GeneratedLinearGradientWgsl {
    const val FEATURE_FLAG = "kanvas.gpu.generatedLinearGradient.enabled"

    fun generateDeterministic(): String = SOURCE.trimIndent() + "\n"

    fun validate(source: String): WgslValidationResult {
        val parsed = parseWgslResult(source)
        val diagnostics = parsed.errors.map { "${it.message} span=${it.span}" }
        return WgslValidationResult(isSuccess = parsed.isSuccess, diagnostics = diagnostics)
    }

    private const val SOURCE = """
// Generated by Kanvas WGSL pipeline generator: Rect + LinearGradient + SrcOver.
struct Uniforms {
    startEnd: vec4f,
    viewport: vec4f,
    countPad: vec4f,
    positions: array<vec4f, 16>,
    colors: array<vec4f, 16>,
    clipShapeBounds: vec4f,
    clipShapeRadiiKind: vec4f,
    colorFilterKindMode: vec4f,
    colorFilterParam0: vec4f,
    colorFilterParam1: vec4f,
    colorFilterParam2: vec4f,
    colorFilterParam3: vec4f,
    colorFilterBias: vec4f,
};

@binding(0) @group(0) var<uniform> uniforms: Uniforms;

@vertex
fn vs_main(@builtin(vertex_index) idx: u32) -> @builtin(position) vec4f {
    let x = f32((idx << 1u) & 2u) * 2.0 - 1.0;
    let y = f32(idx & 2u) * 2.0 - 1.0;
    return vec4f(x, y, 0.0, 1.0);
}

fn compute_t_raw(pos: vec4f) -> f32 {
    let start = uniforms.startEnd.xy;
    let end = uniforms.startEnd.zw;
    let dir = end - start;
    let lenSq = dot(dir, dir);
    if (lenSq < 1.0e-12) {
        return -1.0e30;
    }
    return dot(pos.xy - start, dir) / lenSq;
}

fn sample_stops_at(t: f32) -> vec4f {
    let count = bitcast<u32>(uniforms.countPad.x);
    if (count <= 1u) {
        return uniforms.colors[0];
    }
    let t0 = uniforms.positions[0].x;
    let t1 = uniforms.positions[1].x;
    let span = t1 - t0;
    let u = clamp(select((t - t0) / span, 0.0, span <= 0.0), 0.0, 1.0);
    let inv = 1.0 - u;
    return inv * uniforms.colors[0] + u * uniforms.colors[1];
}

@fragment
fn fs_clamp(@builtin(position) pos: vec4f) -> @location(0) vec4f {
    let t = clamp(compute_t_raw(pos), 0.0, 1.0);
    return sample_stops_at(t);
}
"""
}
