package org.graphiks.math.codegen

import java.nio.file.Files
import java.nio.file.Path
import java.nio.file.StandardCopyOption
import java.util.Comparator
import java.util.UUID
import kotlin.io.path.createDirectories
import kotlin.io.path.exists
import kotlin.io.path.isRegularFile
import kotlin.io.path.readBytes

internal object GeneratedSourceSynchronizer {
    private val ownedRoots = listOf(
        Path.of("math/vector/src/generated/kotlin"),
        Path.of("math/geometry/src/generated/kotlin"),
    )
    private val generatedHeader = (
        "// Generated by :math:geometry-codegen.\n" +
            "// Edit MathPrimitiveManifest.kt and run generateMathPrimitives.\n"
        ).encodeToByteArray()

    fun generate(repoRoot: Path, tree: GeneratedTree) {
        val normalizedFiles = validateAndNormalize(tree)
        val stagingRoot = repoRoot
            .resolve("math/geometry-codegen/build/codegen-staging")
            .resolve(UUID.randomUUID().toString())
        try {
            normalizedFiles.forEach { (relativePath, file) ->
                val staged = stagingRoot.resolve(relativePath)
                staged.parent.createDirectories()
                Files.write(staged, file.utf8)
            }

            val expectedPaths = normalizedFiles.keys
            val staleFiles = existingFiles(repoRoot).filter { it.first !in expectedPaths }
            staleFiles.forEach { (relativePath, absolutePath) ->
                if (!absolutePath.readBytes().startsWith(generatedHeader)) {
                    throw IllegalStateException(
                        "refusing to delete non-generated file from owned root: $relativePath",
                    )
                }
            }

            staleFiles.forEach { (_, absolutePath) -> Files.delete(absolutePath) }
            normalizedFiles.forEach { (relativePath, _) ->
                val destination = repoRoot.resolve(relativePath)
                destination.parent.createDirectories()
                Files.copy(
                    stagingRoot.resolve(relativePath),
                    destination,
                    StandardCopyOption.REPLACE_EXISTING,
                )
            }
            removeEmptyDirectories(repoRoot)
        } finally {
            deleteTree(stagingRoot)
        }
    }

    fun verify(repoRoot: Path, tree: GeneratedTree): List<String> {
        val expected = validateAndNormalize(tree)
        val actual = existingFiles(repoRoot).associate { it.first to it.second }
        return buildList {
            expected.forEach { (relativePath, file) ->
                val actualPath = actual[relativePath]
                when {
                    actualPath == null -> add("missing generated source: $relativePath")
                    !file.utf8.contentEquals(actualPath.readBytes()) ->
                        add("generated source differs: $relativePath")
                }
            }
            actual.keys.filter { it !in expected }.sorted().forEach { relativePath ->
                add("unexpected generated source: $relativePath")
            }
        }.sorted()
    }

    private fun validateAndNormalize(tree: GeneratedTree): Map<Path, GeneratedFile> {
        val normalizedFiles = tree.files.map { file ->
            val path = Path.of(file.relativePath)
            require(!path.isAbsolute) { "generated path must be relative: ${file.relativePath}" }
            require(path == path.normalize()) {
                "generated path must already be normalized: ${file.relativePath}"
            }
            require(ownedRoots.any(path::startsWith)) {
                "generated path is outside owned roots: ${file.relativePath}"
            }
            path to file
        }
        normalizedFiles.groupBy { it.first }
            .filterValues { it.size > 1 }
            .keys
            .sortedBy(Path::toString)
            .firstOrNull()
            ?.let { duplicate ->
                throw IllegalArgumentException("generated path is duplicated after parsing: $duplicate")
            }
        return normalizedFiles.toMap().toSortedMap(compareBy(Path::toString))
    }

    private fun existingFiles(repoRoot: Path): List<Pair<Path, Path>> = ownedRoots
        .flatMap { root ->
            val absoluteRoot = repoRoot.resolve(root)
            if (!absoluteRoot.exists()) {
                emptyList()
            } else {
                Files.walk(absoluteRoot).use { paths ->
                    paths.filter { it.isRegularFile() }
                        .map { root.resolve(absoluteRoot.relativize(it)) to it }
                        .toList()
                }
            }
        }
        .sortedBy { it.first.toString() }

    private fun removeEmptyDirectories(repoRoot: Path) {
        ownedRoots.forEach { root ->
            val absoluteRoot = repoRoot.resolve(root)
            if (!absoluteRoot.exists()) return@forEach
            Files.walk(absoluteRoot).use { paths ->
                paths.sorted(Comparator.reverseOrder()).forEach { path ->
                    if (path != absoluteRoot && Files.isDirectory(path)) {
                        Files.newDirectoryStream(path).use { entries ->
                            if (!entries.iterator().hasNext()) Files.delete(path)
                        }
                    }
                }
            }
        }
    }

    private fun deleteTree(root: Path) {
        if (!root.exists()) return
        Files.walk(root).use { paths ->
            paths.sorted(Comparator.reverseOrder()).forEach(Files::deleteIfExists)
        }
    }

    private fun ByteArray.startsWith(prefix: ByteArray): Boolean =
        size >= prefix.size && prefix.indices.all { this[it] == prefix[it] }
}
