package org.graphiks.math.codegen

import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.PropertySpec
import com.squareup.kotlinpoet.TypeName
import com.squareup.kotlinpoet.TypeSpec

internal object KotlinEmitter {
    private const val GENERATED_HEADER =
        "Generated by :math:geometry-codegen.\n" +
            "Edit MathPrimitiveManifest.kt and run generateMathPrimitives."

    fun emit(schema: PrimitiveSchema): GeneratedTree {
        val files = SemanticModel.expand(schema).flatMap { model ->
            buildList {
                if (model.spec.generateImmutable) add(emitImmutable(model))
                if (model.spec.generateMutable) add(emitMutable(model))
            }
        }.sortedBy { it.relativePath }
        return GeneratedTree(files)
    }

    private fun emitImmutable(model: SemanticPrimitiveModel): GeneratedFile {
        require(model.spec.semantic == Semantic.VECTOR) {
            "Task 2 only emits VECTOR primitives; unsupported semantic ${model.spec.semantic}"
        }
        val scalarType = model.scalar.typeName()
        val vectorType = ClassName(model.packageName, model.typeName)
        val constructor = FunSpec.constructorBuilder().apply {
            model.components.forEach { component -> addParameter(component, scalarType) }
        }.build()
        val vector = TypeSpec.classBuilder(model.typeName)
            .addModifiers(KModifier.PUBLIC)
            .primaryConstructor(constructor)
            .apply {
                model.components.forEach { component ->
                    addProperty(
                        PropertySpec.builder(component, scalarType)
                            .addModifiers(KModifier.PUBLIC)
                            .initializer(component)
                            .build(),
                    )
                }
                addFunction(vectorResultFunction("plus", model, "other", plusExpressions(model)))
                addFunction(vectorResultFunction("minus", model, "other", minusExpressions(model)))
                addFunction(unaryMinusFunction(model))
                addFunction(scalarTimesFunction(model))
                if (model.scalar.id != ScalarId.I32 && Capability.DIVIDE in model.spec.capabilities) {
                    addFunction(scalarDivideFunction(model))
                }
                addFunction(dotFunction(model))
                if (model.spec.dimension == 2) addFunction(cross2Function(model))
                if (model.spec.dimension == 3) addFunction(cross3Function(model))
                addFunction(lengthSquaredFunction(model))
                addFunction(lengthFunction(model))
                if (Capability.NORMALIZE in model.spec.capabilities && model.scalar.id != ScalarId.I32) {
                    addFunction(normalizedFunction(model))
                }
                if (Capability.FINITE_CHECK in model.spec.capabilities) {
                    addFunction(isFiniteFunction(model))
                }
                addFunction(isZeroFunction(model))
                if (model.spec.generateMutable) addFunction(toMutableFunction(model))
                addFunction(equalsFunction(model))
                addFunction(hashCodeFunction(model))
                addFunction(toStringFunction(model))
                addType(companionObject(model))
            }
            .build()

        val file = baseFile(model, model.typeName)
            .apply {
                if (model.scalar.id == ScalarId.I32) {
                    addImport(
                        "org.graphiks.math.scalar",
                        "saturatingAddI32",
                        "saturatingAddI64",
                        "saturatingMultiplyI32",
                        "saturatingNegateI32",
                        "saturatingSubtractI32",
                        "saturatingSubtractI64",
                    )
                }
                addImport("kotlin.math", "abs", "sqrt")
            }
            .addType(vector)
            .addFunction(
                FunSpec.builder("times")
                    .addModifiers(KModifier.PUBLIC, KModifier.OPERATOR)
                    .receiver(scalarType)
                    .addParameter("vector", vectorType)
                    .returns(vectorType)
                    .addStatement("return vector * this")
                    .build(),
            )
            .build()
        return generatedFile(model, model.typeName, file)
    }

    private fun emitMutable(model: SemanticPrimitiveModel): GeneratedFile {
        val scalarType = model.scalar.typeName()
        val immutableType = ClassName(model.packageName, model.typeName)
        val mutableType = ClassName(model.packageName, model.mutableTypeName)
        val constructor = FunSpec.constructorBuilder().apply {
            model.components.forEach { component -> addParameter(component, scalarType) }
        }.build()
        val mutable = TypeSpec.classBuilder(model.mutableTypeName)
            .addModifiers(KModifier.PUBLIC)
            .primaryConstructor(constructor)
            .apply {
                model.components.forEach { component ->
                    addProperty(
                        PropertySpec.builder(component, scalarType)
                            .mutable(true)
                            .addModifiers(KModifier.PUBLIC)
                            .initializer(component)
                            .build(),
                    )
                }
                addFunction(
                    FunSpec.builder("add")
                        .addModifiers(KModifier.PUBLIC)
                        .addParameter("other", immutableType)
                        .apply {
                            model.components.forEach { addStatement("$it += other.$it") }
                        }
                        .build(),
                )
                addFunction(
                    FunSpec.builder("subtract")
                        .addModifiers(KModifier.PUBLIC)
                        .addParameter("other", immutableType)
                        .apply {
                            model.components.forEach { addStatement("$it -= other.$it") }
                        }
                        .build(),
                )
                addFunction(
                    FunSpec.builder("scaleBy")
                        .addModifiers(KModifier.PUBLIC)
                        .addParameter("scalar", scalarType)
                        .apply {
                            model.components.forEach { addStatement("$it *= scalar") }
                        }
                        .build(),
                )
                addFunction(normalizeInPlaceFunction(model, immutableType))
                addFunction(hasSameComponentsFunction(model, mutableType))
                addFunction(hasSameComponentsFunction(model, immutableType))
                addFunction(
                    FunSpec.builder("toImmutable")
                        .addModifiers(KModifier.PUBLIC)
                        .returns(immutableType)
                        .addStatement(
                            "return %T(${model.components.joinToString()})",
                            immutableType,
                        )
                        .build(),
                )
            }
            .build()
        val file = baseFile(model, model.mutableTypeName)
            .addImport("kotlin.math", "abs")
            .addType(mutable)
            .build()
        return generatedFile(model, model.mutableTypeName, file)
    }

    private fun baseFile(model: SemanticPrimitiveModel, fileName: String): FileSpec.Builder =
        FileSpec.builder(model.packageName, fileName).addFileComment(GENERATED_HEADER)

    private fun generatedFile(
        model: SemanticPrimitiveModel,
        fileName: String,
        file: FileSpec,
    ): GeneratedFile {
        val relativePath =
            "${model.generatedRoot}/${model.packageName.replace('.', '/')}/$fileName.kt"
        val source = file.toString().replace("\r\n", "\n").trimEnd('\n') + "\n"
        return GeneratedFile(relativePath, source.encodeToByteArray())
    }

    private fun vectorResultFunction(
        name: String,
        model: SemanticPrimitiveModel,
        parameterName: String,
        expressions: List<String>,
    ): FunSpec {
        val type = ClassName(model.packageName, model.typeName)
        return FunSpec.builder(name)
            .addModifiers(KModifier.PUBLIC, KModifier.OPERATOR)
            .addParameter(parameterName, type)
            .returns(type)
            .addStatement("return %T(${expressions.joinToString()})", type)
            .build()
    }

    private fun plusExpressions(model: SemanticPrimitiveModel): List<String> =
        model.components.map { component ->
            if (model.scalar.id == ScalarId.I32) {
                "saturatingAddI32($component, other.$component)"
            } else {
                "$component + other.$component"
            }
        }

    private fun minusExpressions(model: SemanticPrimitiveModel): List<String> =
        model.components.map { component ->
            if (model.scalar.id == ScalarId.I32) {
                "saturatingSubtractI32($component, other.$component)"
            } else {
                "$component - other.$component"
            }
        }

    private fun unaryMinusFunction(model: SemanticPrimitiveModel): FunSpec {
        val type = ClassName(model.packageName, model.typeName)
        val expressions = model.components.map { component ->
            if (model.scalar.id == ScalarId.I32) "saturatingNegateI32($component)" else "-$component"
        }
        return FunSpec.builder("unaryMinus")
            .addModifiers(KModifier.PUBLIC, KModifier.OPERATOR)
            .returns(type)
            .addStatement("return %T(${expressions.joinToString()})", type)
            .build()
    }

    private fun scalarTimesFunction(model: SemanticPrimitiveModel): FunSpec {
        val type = ClassName(model.packageName, model.typeName)
        val expressions = model.components.map { component ->
            if (model.scalar.id == ScalarId.I32) {
                "saturatingMultiplyI32($component, scalar)"
            } else {
                "$component * scalar"
            }
        }
        return FunSpec.builder("times")
            .addModifiers(KModifier.PUBLIC, KModifier.OPERATOR)
            .addParameter("scalar", model.scalar.typeName())
            .returns(type)
            .addStatement("return %T(${expressions.joinToString()})", type)
            .build()
    }

    private fun scalarDivideFunction(model: SemanticPrimitiveModel): FunSpec {
        val type = ClassName(model.packageName, model.typeName)
        return FunSpec.builder("div")
            .addModifiers(KModifier.PUBLIC, KModifier.OPERATOR)
            .addParameter("scalar", model.scalar.typeName())
            .returns(type)
            .addStatement(
                "return %T(${model.components.joinToString { "$it / scalar" }})",
                type,
            )
            .build()
    }

    private fun dotFunction(model: SemanticPrimitiveModel): FunSpec {
        val type = ClassName(model.packageName, model.typeName)
        val builder = FunSpec.builder("dot")
            .addModifiers(KModifier.PUBLIC)
            .addParameter("other", type)
        if (model.scalar.id == ScalarId.I32) {
            require(model.components.size == 2)
            builder.returns(ClassName("kotlin", "Long"))
                .addCode(
                    "return saturatingAddI64(\n" +
                        "    x.toLong() * other.x.toLong(),\n" +
                        "    y.toLong() * other.y.toLong(),\n" +
                        ")\n",
                )
        } else {
            builder.returns(model.scalar.typeName())
                .addStatement(
                    "return ${model.components.joinToString(" + ") { "$it * other.$it" }}",
                )
        }
        return builder.build()
    }

    private fun cross2Function(model: SemanticPrimitiveModel): FunSpec {
        val type = ClassName(model.packageName, model.typeName)
        val builder = FunSpec.builder("cross")
            .addModifiers(KModifier.PUBLIC)
            .addParameter("other", type)
        if (model.scalar.id == ScalarId.I32) {
            builder.returns(ClassName("kotlin", "Long"))
                .addCode(
                    "return saturatingSubtractI64(\n" +
                        "    x.toLong() * other.y.toLong(),\n" +
                        "    y.toLong() * other.x.toLong(),\n" +
                        ")\n",
                )
        } else {
            builder.returns(model.scalar.typeName())
                .addStatement("return x * other.y - y * other.x")
        }
        return builder.build()
    }

    private fun cross3Function(model: SemanticPrimitiveModel): FunSpec {
        val type = ClassName(model.packageName, model.typeName)
        return FunSpec.builder("cross")
            .addModifiers(KModifier.PUBLIC)
            .addParameter("other", type)
            .returns(type)
            .addStatement(
                "return %T(y * other.z - z * other.y, z * other.x - x * other.z, " +
                    "x * other.y - y * other.x)",
                type,
            )
            .build()
    }

    private fun lengthSquaredFunction(model: SemanticPrimitiveModel): FunSpec {
        val returnType = if (model.scalar.id == ScalarId.I32) {
            ClassName("kotlin", "Long")
        } else {
            model.scalar.typeName()
        }
        val statement = if (model.scalar.id == ScalarId.I32) {
            "return dot(this)"
        } else {
            "return ${model.components.joinToString(" + ") { "$it * $it" }}"
        }
        return FunSpec.builder("lengthSquared")
            .addModifiers(KModifier.PUBLIC)
            .returns(returnType)
            .addStatement(statement)
            .build()
    }

    private fun lengthFunction(model: SemanticPrimitiveModel): FunSpec {
        val returnType = if (model.scalar.id == ScalarId.I32) {
            ClassName("kotlin", "Double")
        } else {
            model.scalar.typeName()
        }
        val sourceComponents = if (model.scalar.id == ScalarId.I32) {
            model.components.map { "$it.toDouble()" }
        } else {
            model.components
        }
        val zero = if (model.scalar.id == ScalarId.F32) "0f" else "0.0"
        val scalarName = returnType.toString()
        return FunSpec.builder("length")
            .addModifiers(KModifier.PUBLIC)
            .returns(returnType)
            .apply {
                if (model.scalar.id != ScalarId.I32) {
                    beginControlFlow(
                        "if (${model.components.joinToString(" || ") { "$it.isNaN()" }})",
                    )
                    addStatement("return $scalarName.NaN")
                    endControlFlow()
                    beginControlFlow(
                        "if (${model.components.joinToString(" || ") { "$it.isInfinite()" }})",
                    )
                    addStatement("return $scalarName.POSITIVE_INFINITY")
                    endControlFlow()
                }
                addStatement(
                    "val scale = maxOf(${sourceComponents.joinToString { "abs($it)" }})",
                )
                beginControlFlow("if (scale == $zero)")
                addStatement("return $zero")
                endControlFlow()
                sourceComponents.zip(model.components).forEach { (source, component) ->
                    addStatement("val scaled${component.uppercase()} = $source / scale")
                }
                val sum = model.components.joinToString(" + ") { component ->
                    "scaled${component.uppercase()} * scaled${component.uppercase()}"
                }
                addStatement("return scale * sqrt($sum)")
            }
            .build()
    }

    private fun normalizedFunction(model: SemanticPrimitiveModel): FunSpec {
        val type = ClassName(model.packageName, model.typeName)
        return FunSpec.builder("normalized")
            .addModifiers(KModifier.PUBLIC)
            .returns(type)
            .addStatement("val length = length()")
            .beginControlFlow("if (!length.isFinite() || abs(length) <= ${model.epsilonLiteral()})")
            .addStatement("return Zero")
            .endControlFlow()
            .addStatement(
                "return %T(${model.components.joinToString { "$it / length" }})",
                type,
            )
            .build()
    }

    private fun isFiniteFunction(model: SemanticPrimitiveModel): FunSpec =
        FunSpec.builder("isFinite")
            .addModifiers(KModifier.PUBLIC)
            .returns(ClassName("kotlin", "Boolean"))
            .addStatement(
                "return ${model.components.joinToString(" && ") { "$it.isFinite()" }}",
            )
            .build()

    private fun isZeroFunction(model: SemanticPrimitiveModel): FunSpec {
        val expression = if (model.scalar.id == ScalarId.I32) {
            model.components.joinToString(" && ") { "$it == 0" }
        } else {
            model.components.joinToString(" && ") { "abs($it) <= ${model.epsilonLiteral()}" }
        }
        return FunSpec.builder("isZero")
            .addModifiers(KModifier.PUBLIC)
            .returns(ClassName("kotlin", "Boolean"))
            .addStatement("return $expression")
            .build()
    }

    private fun toMutableFunction(model: SemanticPrimitiveModel): FunSpec =
        FunSpec.builder("toMutable")
            .addModifiers(KModifier.PUBLIC)
            .returns(ClassName(model.packageName, model.mutableTypeName))
            .addStatement(
                "return %T(${model.components.joinToString()})",
                ClassName(model.packageName, model.mutableTypeName),
            )
            .build()

    private fun equalsFunction(model: SemanticPrimitiveModel): FunSpec {
        val type = ClassName(model.packageName, model.typeName)
        val comparisons = if (model.scalar.id == ScalarId.I32) {
            model.components.joinToString(" && ") { "$it == other.$it" }
        } else {
            model.components.joinToString(" && ") { "$it.toBits() == other.$it.toBits()" }
        }
        return FunSpec.builder("equals")
            .addModifiers(KModifier.PUBLIC, KModifier.OVERRIDE)
            .addParameter("other", ClassName("kotlin", "Any").copy(nullable = true))
            .returns(ClassName("kotlin", "Boolean"))
            .addStatement("return other is %T && $comparisons", type)
            .build()
    }

    private fun hashCodeFunction(model: SemanticPrimitiveModel): FunSpec {
        val expression = model.components
            .map { "$it.hashCode()" }
            .reduce { accumulated, next -> "31 * ($accumulated) + $next" }
            .replace("31 * (x.hashCode())", "31 * x.hashCode()")
        return FunSpec.builder("hashCode")
            .addModifiers(KModifier.PUBLIC, KModifier.OVERRIDE)
            .returns(ClassName("kotlin", "Int"))
            .addStatement("return $expression")
            .build()
    }

    private fun toStringFunction(model: SemanticPrimitiveModel): FunSpec {
        val template = model.typeName + model.components.joinToString(
            prefix = "(",
            postfix = ")",
        ) { "$it=\$$it" }
        return FunSpec.builder("toString")
            .addModifiers(KModifier.PUBLIC, KModifier.OVERRIDE)
            .returns(ClassName("kotlin", "String"))
            .addStatement("return \"$template\"")
            .build()
    }

    private fun companionObject(model: SemanticPrimitiveModel): TypeSpec {
        val type = ClassName(model.packageName, model.typeName)
        val zero = model.zeroLiteral()
        return TypeSpec.companionObjectBuilder()
            .apply {
                addProperty(
                    PropertySpec.builder("Zero", type)
                        .addModifiers(KModifier.PUBLIC)
                        .initializer("%T(${model.components.joinToString { zero }})", type)
                        .build(),
                )
                model.components.forEachIndexed { axis, component ->
                    val values = model.components.mapIndexed { index, _ ->
                        if (index == axis) model.oneLiteral() else zero
                    }
                    addProperty(
                        PropertySpec.builder("Unit${component.uppercase()}", type)
                            .addModifiers(KModifier.PUBLIC)
                            .initializer("%T(${values.joinToString()})", type)
                            .build(),
                    )
                }
            }
            .build()
    }

    private fun normalizeInPlaceFunction(
        model: SemanticPrimitiveModel,
        immutableType: ClassName,
    ): FunSpec = FunSpec.builder("normalizeInPlace")
        .addModifiers(KModifier.PUBLIC)
        .returns(ClassName("kotlin", "Boolean"))
        .addStatement(
            "val length = %T(${model.components.joinToString()}).length()",
            immutableType,
        )
        .beginControlFlow("if (!length.isFinite() || abs(length) <= ${model.epsilonLiteral()})")
        .addStatement("return false")
        .endControlFlow()
        .apply {
            model.components.forEach { addStatement("$it /= length") }
        }
        .addStatement("return true")
        .build()

    private fun hasSameComponentsFunction(
        model: SemanticPrimitiveModel,
        otherType: ClassName,
    ): FunSpec = FunSpec.builder("hasSameComponentsAs")
        .addModifiers(KModifier.PUBLIC)
        .addParameter("other", otherType)
        .returns(ClassName("kotlin", "Boolean"))
        .addStatement(
            "return ${model.components.joinToString(" && ") { "$it == other.$it" }}",
        )
        .build()

    private fun ScalarSpec.typeName(): TypeName = ClassName("kotlin", kotlinType)

    private fun SemanticPrimitiveModel.zeroLiteral(): String = when (scalar.id) {
        ScalarId.F32 -> "0f"
        ScalarId.F64 -> "0.0"
        ScalarId.I32 -> "0"
    }

    private fun SemanticPrimitiveModel.oneLiteral(): String = when (scalar.id) {
        ScalarId.F32 -> "1f"
        ScalarId.F64 -> "1.0"
        ScalarId.I32 -> "1"
    }

    private fun SemanticPrimitiveModel.epsilonLiteral(): String = when (scalar.id) {
        ScalarId.F32 -> "1e-7f"
        ScalarId.F64 -> "1e-12"
        ScalarId.I32 -> error("I32 does not have a floating-point epsilon")
    }
}
