package org.graphiks.math.codegen

import java.nio.file.Path
import kotlin.io.path.createDirectories
import kotlin.io.path.createTempDirectory
import kotlin.io.path.exists
import kotlin.io.path.readBytes
import kotlin.io.path.writeBytes
import kotlin.io.path.writeText
import kotlin.test.Test
import kotlin.test.assertContentEquals
import kotlin.test.assertContains
import kotlin.test.assertFailsWith
import kotlin.test.assertFalse
import kotlin.test.assertTrue

class GeneratedSourceSynchronizerTest {
    @Test
    fun `generated tree rejects duplicate paths`() {
        val file = generatedFile("Vector2F32.kt", "first")

        val error = assertFailsWith<IllegalArgumentException> {
            GeneratedTree(listOf(file, file.copy(utf8 = "second".encodeToByteArray())))
        }

        assertContains(error.message.orEmpty(), file.relativePath)
    }

    @Test
    fun `generation rejects paths that alias after parsing`() = withTempRepo { repoRoot ->
        val first = generatedFile("Vector2F32.kt", "first")
        val alias = first.copy(
            relativePath = first.relativePath.replace("/org/", "/org//"),
            utf8 = generatedSource("second"),
        )

        val error = assertFailsWith<IllegalArgumentException> {
            GeneratedSourceSynchronizer.generate(repoRoot, GeneratedTree(listOf(first, alias)))
        }

        assertContains(error.message.orEmpty(), first.relativePath)
    }

    @Test
    fun `generation rejects output outside owned roots`() = withTempRepo { repoRoot ->
        val tree = GeneratedTree(
            listOf(GeneratedFile("math/scalar/src/commonMain/kotlin/Evil.kt", generatedSource("evil"))),
        )

        val error = assertFailsWith<IllegalArgumentException> {
            GeneratedSourceSynchronizer.generate(repoRoot, tree)
        }

        assertContains(error.message.orEmpty(), "math/scalar/src/commonMain/kotlin/Evil.kt")
    }

    @Test
    fun `generation rejects normalized path escaping owned root`() = withTempRepo { repoRoot ->
        val relativePath = "math/vector/src/generated/kotlin/../commonMain/kotlin/Evil.kt"
        val tree = GeneratedTree(listOf(GeneratedFile(relativePath, generatedSource("evil"))))

        val error = assertFailsWith<IllegalArgumentException> {
            GeneratedSourceSynchronizer.generate(repoRoot, tree)
        }

        assertContains(error.message.orEmpty(), relativePath)
    }

    @Test
    fun `generation refuses to delete handwritten file from owned root`() = withTempRepo { repoRoot ->
        val stale = repoRoot.resolve(
            "math/vector/src/generated/kotlin/org/graphiks/math/vector/Handwritten.kt",
        )
        stale.parent.createDirectories()
        stale.writeText("package org.graphiks.math.vector\n")

        val error = assertFailsWith<IllegalStateException> {
            GeneratedSourceSynchronizer.generate(repoRoot, GeneratedTree(emptyList()))
        }

        assertContains(error.message.orEmpty(), "Handwritten.kt")
        assertTrue(stale.exists())
    }

    @Test
    fun `generation deletes obsolete generated file`() = withTempRepo { repoRoot ->
        val stale = repoRoot.resolve(
            "math/vector/src/generated/kotlin/org/graphiks/math/vector/Obsolete.kt",
        )
        stale.parent.createDirectories()
        stale.writeBytes(generatedSource("obsolete"))

        GeneratedSourceSynchronizer.generate(repoRoot, GeneratedTree(emptyList()))

        assertFalse(stale.exists())
    }

    @Test
    fun `generation synchronizes exact bytes`() = withTempRepo { repoRoot ->
        val expected = generatedFile("Vector2F32.kt", "expected")

        GeneratedSourceSynchronizer.generate(repoRoot, GeneratedTree(listOf(expected)))

        assertContentEquals(expected.utf8, repoRoot.resolve(expected.relativePath).readBytes())
    }

    @Test
    fun `verify reports drift without modifying any byte`() = withTempRepo { repoRoot ->
        val expected = generatedFile("Vector2F32.kt", "expected")
        val destination = repoRoot.resolve(expected.relativePath)
        destination.parent.createDirectories()
        val original = generatedSource("different")
        destination.writeBytes(original)

        val differences = GeneratedSourceSynchronizer.verify(repoRoot, GeneratedTree(listOf(expected)))

        assertTrue(differences.isNotEmpty())
        assertContentEquals(original, destination.readBytes())
    }

    private fun generatedFile(fileName: String, body: String): GeneratedFile = GeneratedFile(
        "math/vector/src/generated/kotlin/org/graphiks/math/vector/$fileName",
        generatedSource(body),
    )

    private fun generatedSource(body: String): ByteArray = (
        "// Generated by :math:geometry-codegen.\n" +
            "// Edit MathPrimitiveManifest.kt and run generateMathPrimitives.\n" +
            "$body\n"
        ).encodeToByteArray()

    private fun withTempRepo(block: (Path) -> Unit) {
        val repoRoot = createTempDirectory("generated-source-synchronizer-test-")
        try {
            block(repoRoot)
        } finally {
            repoRoot.toFile().deleteRecursively()
        }
    }
}
