package org.graphiks.math.codegen

import kotlin.test.Test
import kotlin.test.assertContentEquals
import kotlin.test.assertContains
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertTrue

class KotlinEmitterTest {
    @Test
    fun `same schema emits byte-identical sorted files`() {
        val first = KotlinEmitter.emit(MathPrimitiveManifest.schema)
        val second = KotlinEmitter.emit(MathPrimitiveManifest.schema)

        assertEquals(first.files.map { it.relativePath }.sorted(), first.files.map { it.relativePath })
        assertContentEquals(
            first.files.flatMap { it.utf8.asIterable() },
            second.files.flatMap { it.utf8.asIterable() },
        )
    }

    @Test
    fun `manifest emits only the selected vector inventory`() {
        assertEquals(
            listOf(
                "math/vector/src/generated/kotlin/org/graphiks/math/vector/MutableVector2F32.kt",
                "math/vector/src/generated/kotlin/org/graphiks/math/vector/MutableVector2F64.kt",
                "math/vector/src/generated/kotlin/org/graphiks/math/vector/MutableVector3F32.kt",
                "math/vector/src/generated/kotlin/org/graphiks/math/vector/Vector2F32.kt",
                "math/vector/src/generated/kotlin/org/graphiks/math/vector/Vector2F64.kt",
                "math/vector/src/generated/kotlin/org/graphiks/math/vector/Vector2I32.kt",
                "math/vector/src/generated/kotlin/org/graphiks/math/vector/Vector3F32.kt",
                "math/vector/src/generated/kotlin/org/graphiks/math/vector/Vector4F32.kt",
            ),
            KotlinEmitter.emit(MathPrimitiveManifest.schema).files.map { it.relativePath },
        )
    }

    @Test
    fun `fallback surface excludes data class conveniences`() {
        val source = emitted("Vector2F32.kt")

        assertTrue(
            source.startsWith(
                "// Generated by :math:geometry-codegen.\n" +
                    "// Edit MathPrimitiveManifest.kt and run generateMathPrimitives.\n",
            ),
        )
        assertContains(source, "package org.graphiks.math.vector")
        assertContains(source, "public class Vector2F32(")
        assertContains(source, "public val x: Float")
        assertContains(source, "public val y: Float")
        assertFalse("data class" in source)
        assertFalse("fun copy(" in source)
        assertFalse("component1" in source)
        assertFalse("fun of(" in source)
        assertFalse("this === other" in source)
        assertContains(
            source,
            "override fun toString(): String = \"Vector2F32(x=\$x, y=\$y)\"",
        )
        assertFalse("Generated on" in source)
        assertFalse("/Users/" in source)
    }

    @Test
    fun `all emitted sources use LF and one final newline`() {
        KotlinEmitter.emit(MathPrimitiveManifest.schema).files.forEach { file ->
            val source = file.utf8.decodeToString()
            assertFalse('\r' in source, file.relativePath)
            assertTrue(source.endsWith("\n"), file.relativePath)
            assertFalse(source.endsWith("\n\n"), file.relativePath)
        }
    }

    private fun emitted(fileName: String): String =
        KotlinEmitter.emit(MathPrimitiveManifest.schema).files
            .single { it.relativePath.endsWith("/$fileName") }
            .utf8
            .decodeToString()
}
