// Generated by WebGPU-KTypes WGSL Backend
struct Struct_2 {
    color: vec4<f32>,
    outerBounds: vec4<f32>,
    innerBounds: vec4<f32>,
    clipShapeBounds: vec4<f32>,
    clipShapeRadiiKind: vec4<f32>,
    colorFilterKindMode: vec4<f32>,
    colorFilterParam0: vec4<f32>,
    colorFilterParam1: vec4<f32>,
    colorFilterParam2: vec4<f32>,
    colorFilterParam3: vec4<f32>,
    colorFilterBias: vec4<f32>,
}
@group(0) @binding(0)
var<uniform> uniforms: Struct_2;

fn rrect_cov(p: vec2<f32>, bounds: vec4<f32>, rx_in: f32, ry_in: f32) -> f32 {
    var centre: vec2<f32> = vec2<f32>((0.5f * (bounds[0] + bounds[2])), (0.5f * (bounds[1] + bounds[3])));
    var half: vec2<f32> = vec2<f32>((0.5f * (bounds[2] - bounds[0])), (0.5f * (bounds[3] - bounds[1])));
    var rx: f32 = max(rx_in, 1.0E-4f);
    var ry: f32 = max(ry_in, 1.0E-4f);
    var q_abs: vec2<f32> = abs((p - centre));
    var q: vec2<f32> = (q_abs - (half - vec2<f32>(rx, ry)));
    var inner_rect_sdf: f32 = max(q[0], q[1]);
    var outer_rect_sdf: f32 = max((q_abs[0] - half[0]), (q_abs[1] - half[1]));
    var qm: vec2<f32> = max(q, vec2<f32>(0.0f, 0.0f));
    var n: vec2<f32> = vec2<f32>((qm[0] / rx), (qm[1] / ry));
    var nl: vec2<f32> = length(n);
    var nl_safe: vec2<f32> = max(nl, 1.0E-6f);
    var dir: vec2<f32> = (n / nl_safe);
    var effective_r: vec2<f32> = length(vec2<f32>((rx * dir[0]), (ry * dir[1])));
    var corner_sdf: vec2<f32> = ((nl - 1.0f) * effective_r);
    var in_corner_band: f32 = (step(0.0f, q[0]) * step(0.0f, q[1]));
    var band_sdf: f32 = mix(outer_rect_sdf, corner_sdf, in_corner_band);
    var final_sdf: f32 = band_sdf;
    return clamp((0.5f - final_sdf), 0.0f, 1.0f);
}

fn blend_premul(s: vec4<f32>, d: vec4<f32>, mode: u32) -> vec4<f32> {
    var sa: f32 = s[3];
    var da: f32 = d[3];
    if ((mode == 0u)) {
        return vec4<f32>(0.0f);
    }
    if ((mode == 1u)) {
        return s;
    }
    if ((mode == 2u)) {
        return d;
    }
    if ((mode == 3u)) {
        var k: f32 = (1.0f - sa);
        return vec4<f32>((s[0] + (d[0] * k)), (s[1] + (d[1] * k)), (s[2] + (d[2] * k)), (sa + (da * k)));
    }
    if ((mode == 4u)) {
        var k: f32 = (1.0f - da);
        return vec4<f32>((d[0] + (s[0] * k)), (d[1] + (s[1] * k)), (d[2] + (s[2] * k)), (da + (sa * k)));
    }
    if ((mode == 5u)) {
        return (s * da);
    }
    if ((mode == 6u)) {
        return (d * sa);
    }
    if ((mode == 7u)) {
        return (s * (1.0f - da));
    }
    if ((mode == 8u)) {
        return (d * (1.0f - sa));
    }
    if ((mode == 9u)) {
        var k: f32 = (1.0f - sa);
        return vec4<f32>(((s[0] * da) + (d[0] * k)), ((s[1] * da) + (d[1] * k)), ((s[2] * da) + (d[2] * k)), ((sa * da) + (da * k)));
    }
    if ((mode == 10u)) {
        var k: f32 = (1.0f - da);
        return vec4<f32>(((d[0] * sa) + (s[0] * k)), ((d[1] * sa) + (s[1] * k)), ((d[2] * sa) + (s[2] * k)), ((da * sa) + (sa * k)));
    }
    if ((mode == 11u)) {
        var ks: f32 = (1.0f - sa);
        var kd: f32 = (1.0f - da);
        return vec4<f32>(((s[0] * kd) + (d[0] * ks)), ((s[1] * kd) + (d[1] * ks)), ((s[2] * kd) + (d[2] * ks)), ((sa * kd) + (da * ks)));
    }
    if ((mode == 12u)) {
        return min(vec4<f32>(1.0f), (s + d));
    }
    if ((mode == 13u)) {
        return (s * d);
    }
    if ((mode == 14u)) {
        return ((s + d) - (s * d));
    }
    return s;
}

fn apply_color_filter(c_un: vec4<f32>) -> vec4<f32> {
    var kind: u32 = u32((uniforms.colorFilterKindMode[0] + 0.5f));
    if ((kind == 1u)) {
        var mode: u32 = u32((uniforms.colorFilterKindMode[1] + 0.5f));
        var a: f32 = c_un[3];
        var dst_premul: vec4<f32> = vec4<f32>((c_un[0] * a), (c_un[1] * a), (c_un[2] * a), a);
        var out_premul: vec4<f32> = blend_premul(uniforms.colorFilterParam0, dst_premul, mode);
        var oa: f32 = out_premul[3];
        if ((oa <= 0.0f)) {
            return vec4<f32>(0.0f);
        }
        var inv: f32 = (1.0f / oa);
        return vec4<f32>((out_premul[0] * inv), (out_premul[1] * inv), (out_premul[2] * inv), oa);
    }
    if ((kind == 2u)) {
        var out_r: vec4<f32> = (dot(uniforms.colorFilterParam0, c_un) + uniforms.colorFilterBias[0]);
        var out_g: vec4<f32> = (dot(uniforms.colorFilterParam1, c_un) + uniforms.colorFilterBias[1]);
        var out_b: vec4<f32> = (dot(uniforms.colorFilterParam2, c_un) + uniforms.colorFilterBias[2]);
        var out_a: vec4<f32> = (dot(uniforms.colorFilterParam3, c_un) + uniforms.colorFilterBias[3]);
        return vec4<f32>(clamp(out_r, 0.0f, 1.0f), clamp(out_g, 0.0f, 1.0f), clamp(out_b, 0.0f, 1.0f), clamp(out_a, 0.0f, 1.0f));
    }
    return c_un;
}

@vertex
fn vs_main(@builtin(vertex_index) idx: u32) -> vec4<f32> {
    var x: f32 = ((f32(((idx << 1u) & 2u)) * 2.0f) - 1.0f);
    var y: f32 = ((f32((idx & 2u)) * 2.0f) - 1.0f);
    return vec4<f32>(x, y, 0.0f, 1.0f);
}

@fragment
fn fs_main(@builtin(position) pos: vec4<f32>) -> vec4<f32> {
    var ob: vec4<f32> = uniforms.outerBounds;
    var outer_cov_x: f32 = clamp((min((pos[0] + 0.5f), ob[2]) - max((pos[0] - 0.5f), ob[0])), 0.0f, 1.0f);
    var outer_cov_y: f32 = clamp((min((pos[1] + 0.5f), ob[3]) - max((pos[1] - 0.5f), ob[1])), 0.0f, 1.0f);
    var ib: vec4<f32> = uniforms.innerBounds;
    var inner_cov_x: f32 = clamp((min((pos[0] + 0.5f), ib[2]) - max((pos[0] - 0.5f), ib[0])), 0.0f, 1.0f);
    var inner_cov_y: f32 = clamp((min((pos[1] + 0.5f), ib[3]) - max((pos[1] - 0.5f), ib[1])), 0.0f, 1.0f);
    var coverage: f32 = max(0.0f, ((outer_cov_x * outer_cov_y) - (inner_cov_x * inner_cov_y)));
    var clip_kind: i32 = i32((uniforms.clipShapeRadiiKind[2] + 0.5f));
    if ((clip_kind == 1)) {
        var clip_cov: f32 = rrect_cov(pos.xy, uniforms.clipShapeBounds, uniforms.clipShapeRadiiKind[0], uniforms.clipShapeRadiiKind[1]);
        coverage = (coverage * clip_cov);
    } else {
        if ((clip_kind == 2)) {
            var clip_cov: f32 = rrect_cov(pos.xy, uniforms.clipShapeBounds, uniforms.clipShapeRadiiKind[0], uniforms.clipShapeRadiiKind[1]);
            coverage = (coverage * (1.0f - clip_cov));
        }
    }
    var c: vec4<f32> = apply_color_filter(uniforms.color);
    var a: f32 = (c[3] * coverage);
    return vec4<f32>((c.xyz * a), a);
}
