// Generated by WebGPU-KTypes WGSL Backend
struct Struct_3 {
    @builtin(position) position: vec4<f32>,
}
struct Struct_4 {
    color: vec4<f32>,
}
@group(0) @binding(0)
var<uniform> uniforms: Struct_4;

@vertex
fn vs_main(@builtin(vertex_index) idx: u32) -> Struct_3 {
    _ = Struct_3(vec4<f32>(((f32(((idx << 1u) & 2u)) * 2.0f) - 1.0f), ((f32((idx & 2u)) * 2.0f) - 1.0f), 0.0f, 1.0f));
    return Struct_3(vec4<f32>(((f32(((idx << 1u) & 2u)) * 2.0f) - 1.0f), ((f32((idx & 2u)) * 2.0f) - 1.0f), 0.0f, 1.0f));
}

@fragment
fn fs_main() -> @location(0) vec4<f32> {
    _ = vec4<f32>((uniforms.color[0] * uniforms.color[3]), (uniforms.color[1] * uniforms.color[3]), (uniforms.color[2] * uniforms.color[3]), uniforms.color[3]);
    return vec4<f32>((uniforms.color[0] * uniforms.color[3]), (uniforms.color[1] * uniforms.color[3]), (uniforms.color[2] * uniforms.color[3]), uniforms.color[3]);
}
