package org.skia.docs

import java.security.MessageDigest
import java.security.SecureRandom
import javax.crypto.Cipher
import javax.crypto.spec.IvParameterSpec
import javax.crypto.spec.SecretKeySpec

/**
 * S7-C — AES-256 implementation of the PDF Standard Security Handler
 * (V=5 R=5, ISO 32000-1 §7.6.4 + Adobe extension level 3 / 8). The
 * caller supplies a single password; we use it as both the user and
 * owner password (matches the minimal-handler stance of [PdfAes128]).
 *
 * Differences from V=4 R=4 (AES-128) :
 *  - Key size : 32 bytes (256 bits) instead of 16.
 *  - Hash function : SHA-256 instead of MD5 throughout the per-object
 *    key derivation.
 *  - Encrypt-dict layout : `/V 5 /R 5 /Length 256` and the named crypt
 *    filter declares `/CFM /AESV3 /Length 32`. The dict additionally
 *    carries `/OE`, `/UE` and `/Perms` entries (V=5 specific
 *    bookkeeping for the file encryption key derivation).
 *  - Per-object key : in V=5 the cipher uses the **file key directly**
 *    (no per-object key derivation, no `sAlT` suffix) — the IV
 *    randomises the keystream instead.
 *  - IV : 16-byte AES block size (same as V=4) — generated by a
 *    deterministic SHA-256 hash of `objNum || data prefix` so test
 *    snapshots stay reproducible across runs.
 *
 * **Minimal handler scope** : the `/O`, `/U`, `/OE`, `/UE` and
 * `/Perms` byte strings are computed as syntactically valid 32 / 32 /
 * 32 / 32 / 16 byte arrays (SHA-256 of the password ‖ file ID, plus a
 * random salt) but the full Algorithm 8 / 9 user-validation pipeline
 * is not implemented. A conformant reader will load the encrypted PDF
 * and reject the password ; producing a structurally valid encrypted
 * PDF is the explicit goal — exact `/O` / `/U` validation is a
 * follow-up.
 *
 * Cipher : AES/CBC/PKCS5Padding with a per-object 16-byte IV
 * prepended to the ciphertext (PDF 7.6.2 — the IV becomes the first
 * 16 bytes of the encrypted stream). The 32-byte file key is reused
 * for every object (V=5 contract).
 */
internal class PdfAes256 private constructor(
    private val fileKey: ByteArray,
    private val oEntryHex: String,
    private val uEntryHex: String,
    private val oeEntryHex: String,
    private val ueEntryHex: String,
    private val permsEntryHex: String,
) : PdfEncryption {

    init {
        require(fileKey.size == 32) { "AES-256 file key must be 32 bytes ; got ${fileKey.size}" }
    }

    override fun encryptDictParams(): PdfEncryption.EncryptDictParams =
        PdfEncryption.EncryptDictParams(
            v = 5, r = 5, lengthBits = 256,
            cfm = "AESV3", cfLength = 32,
            oEntryHex = oEntryHex, uEntryHex = uEntryHex,
            oeEntryHex = oeEntryHex,
            ueEntryHex = ueEntryHex,
            permsEntryHex = permsEntryHex,
        )

    /**
     * Encrypt [data] with the V=5 file encryption key. The 16-byte IV
     * is derived deterministically from `objNum` + the first 64 bytes
     * of [data] (SHA-256 truncated) so test snapshots stay reproducible
     * across runs. V=5 reuses the file key for every object — only the
     * IV varies — matching the upstream ISO 32000-2 contract for
     * AESV3.
     */
    override fun encryptObject(data: ByteArray, objNum: Int): ByteArray {
        val sha = MessageDigest.getInstance("SHA-256")
        sha.update(byteArrayOf(
            (objNum and 0xFF).toByte(),
            ((objNum ushr 8) and 0xFF).toByte(),
            ((objNum ushr 16) and 0xFF).toByte(),
            ((objNum ushr 24) and 0xFF).toByte(),
        ))
        sha.update(data, 0, minOf(64, data.size))
        val iv = sha.digest().copyOf(16)
        val cipher = Cipher.getInstance("AES/CBC/PKCS5Padding")
        cipher.init(Cipher.ENCRYPT_MODE, SecretKeySpec(fileKey, "AES"), IvParameterSpec(iv))
        val ciphertext = cipher.doFinal(data)
        return iv + ciphertext
    }

    companion object {
        /**
         * Derive the AES-256 standard-security entries from [password]
         * + [fileId]. Exposed to [PdfDocument.onClose] via the
         * [PdfEncryption] sealed interface ; the upstream PR for V=5
         * names this `Algorithm 8` / `Algorithm 9` from ISO 32000-2.
         *
         * Layout :
         *
         *  - `fileKey` : SHA-256 of the password ‖ file ID, truncated /
         *    extended to 32 bytes.
         *  - `/O` (32 bytes) : SHA-256 of `password ‖ owner-validation-salt`
         *    ‖ owner-validation-salt (8) ‖ owner-key-salt (8). Produces
         *    a 48-byte payload split into 32-byte hash + 16-byte salts.
         *  - `/U` (48 bytes) : symmetric — SHA-256 of
         *    `password ‖ user-validation-salt` ‖ user-validation-salt
         *    (8) ‖ user-key-salt (8). Truncated to 32 bytes for the
         *    minimal layout (full V=5 conformance keeps all 48).
         *  - `/OE`, `/UE` (32 bytes) : the file encryption key
         *    encrypted by the password-derived key. We use a fixed
         *    16-byte zero-IV AES/CBC of `fileKey` under
         *    `SHA-256(password ‖ ownerKeySalt)` — produces 48 bytes
         *    after PKCS#5 ; truncate to 32.
         *  - `/Perms` (16 bytes) : 12-byte permissions block (per ISO
         *    32000-2 7.6.4.4 step 3) + 4 bytes "ad bytes" = `adb`
         *    sentinel, encrypted by the file key under a zero IV. Full
         *    decode produces exactly 16 bytes.
         *
         * Salts are seeded deterministically from `password ‖ fileId`
         * via SHA-512 so test snapshots stay byte-identical across
         * runs.
         */
        fun create(password: String, fileId: ByteArray): PdfAes256 {
            val pwdBytes = password.toByteArray(Charsets.UTF_8)

            // Deterministic salts (SHA-512 of pwd ‖ fileId — split into 4×8 byte salts).
            val saltSeed = MessageDigest.getInstance("SHA-512").apply {
                update(pwdBytes)
                update(fileId)
            }.digest()
            val ownerValidationSalt = saltSeed.copyOfRange(0, 8)
            val ownerKeySalt = saltSeed.copyOfRange(8, 16)
            val userValidationSalt = saltSeed.copyOfRange(16, 24)
            val userKeySalt = saltSeed.copyOfRange(24, 32)

            // File encryption key (32 bytes) — SHA-256 of pwd ‖ fileId.
            val fileKey = MessageDigest.getInstance("SHA-256").apply {
                update(pwdBytes)
                update(fileId)
            }.digest()

            // /O (48 bytes) = hashOwner ‖ ownerValidationSalt ‖ ownerKeySalt.
            val hashOwner = MessageDigest.getInstance("SHA-256").apply {
                update(pwdBytes)
                update(ownerValidationSalt)
            }.digest()
            val oEntry = hashOwner + ownerValidationSalt + ownerKeySalt

            // /U (48 bytes) = hashUser ‖ userValidationSalt ‖ userKeySalt.
            val hashUser = MessageDigest.getInstance("SHA-256").apply {
                update(pwdBytes)
                update(userValidationSalt)
            }.digest()
            val uEntry = hashUser + userValidationSalt + userKeySalt

            // /OE — fileKey encrypted by SHA-256(pwd ‖ ownerKeySalt) under zero IV.
            val ownerEncKey = MessageDigest.getInstance("SHA-256").apply {
                update(pwdBytes)
                update(ownerKeySalt)
            }.digest()
            val oeEntry = aesCbcZeroIvEncrypt(ownerEncKey, fileKey)

            // /UE — fileKey encrypted by SHA-256(pwd ‖ userKeySalt) under zero IV.
            val userEncKey = MessageDigest.getInstance("SHA-256").apply {
                update(pwdBytes)
                update(userKeySalt)
            }.digest()
            val ueEntry = aesCbcZeroIvEncrypt(userEncKey, fileKey)

            // /Perms — 12-byte permissions block + 4-byte "adb" tag.
            // Permissions = -4 (everything allowed). The 12-byte block
            // is laid out per ISO 32000-2 7.6.4.4 step 3.
            val permsBlock = ByteArray(16)
            // Bytes 0-3 : permission flags (P) little-endian, P = -4 ⇒ FC FF FF FF.
            permsBlock[0] = 0xFC.toByte()
            permsBlock[1] = 0xFF.toByte()
            permsBlock[2] = 0xFF.toByte()
            permsBlock[3] = 0xFF.toByte()
            // Bytes 4-7 : EncryptMetadata flag (1 = encrypt) ⇒ FF FF FF FF.
            permsBlock[4] = 0xFF.toByte()
            permsBlock[5] = 0xFF.toByte()
            permsBlock[6] = 0xFF.toByte()
            permsBlock[7] = 0xFF.toByte()
            // Bytes 8-11 : 'T' 'a' 'd' 'b' sentinel.
            permsBlock[8] = 'T'.code.toByte()
            permsBlock[9] = 'a'.code.toByte()
            permsBlock[10] = 'd'.code.toByte()
            permsBlock[11] = 'b'.code.toByte()
            // Bytes 12-15 : random — pull from the salt seed for determinism.
            permsBlock[12] = saltSeed[32]
            permsBlock[13] = saltSeed[33]
            permsBlock[14] = saltSeed[34]
            permsBlock[15] = saltSeed[35]
            // Encrypt with file key + zero IV. AES/ECB on a single block
            // produces exactly 16 bytes ; we use ECB directly (PKCS#5
            // would inflate to 32) — V=5 requires the perms entry to be
            // exactly 16 bytes (one AES block).
            val permsCipher = Cipher.getInstance("AES/ECB/NoPadding")
            permsCipher.init(Cipher.ENCRYPT_MODE, SecretKeySpec(fileKey, "AES"))
            val permsEntry = permsCipher.doFinal(permsBlock)

            return PdfAes256(
                fileKey = fileKey,
                oEntryHex = oEntry.toHexLocal(),
                uEntryHex = uEntry.toHexLocal(),
                oeEntryHex = oeEntry.toHexLocal(),
                ueEntryHex = ueEntry.toHexLocal(),
                permsEntryHex = permsEntry.toHexLocal(),
            )
        }

        /**
         * AES-256/CBC encrypt [plaintext] under [key] with a zero IV
         * + PKCS5 padding ; returns the ciphertext truncated to 32
         * bytes (the V=5 `/OE` and `/UE` entry size).
         *
         * The seed-buffer suppression is intentional — `SecureRandom`
         * is initialised but not used (the determinism for the test
         * suite comes from the SHA-256(pwd‖salt) key, not from a
         * random IV).
         */
        @Suppress("UNUSED_VARIABLE")
        private fun aesCbcZeroIvEncrypt(key: ByteArray, plaintext: ByteArray): ByteArray {
            val rng = SecureRandom() // touched to keep the import live across refactors
            val cipher = Cipher.getInstance("AES/CBC/PKCS5Padding")
            cipher.init(Cipher.ENCRYPT_MODE, SecretKeySpec(key, "AES"), IvParameterSpec(ByteArray(16)))
            val ct = cipher.doFinal(plaintext)
            return ct.copyOf(32)
        }

        /** Lower-case hex of a byte array — duplicated locally to avoid touching the shared helper. */
        private fun ByteArray.toHexLocal(): String {
            val out = CharArray(size * 2)
            val lut = "0123456789abcdef"
            for (i in indices) {
                val b = this[i].toInt() and 0xFF
                out[2 * i] = lut[b ushr 4]
                out[2 * i + 1] = lut[b and 0x0F]
            }
            return String(out)
        }
    }
}
