package org.skia.tests

import org.skia.core.SkCanvas
import org.skia.math.SK_ColorCYAN
import org.skia.foundation.SkBitmap
import org.skia.foundation.SkBlurMaskFilter
import org.skia.foundation.SkBlurStyle
import org.skia.foundation.SkColorFilter
import org.skia.foundation.SkColorFilters
import org.skia.foundation.SkImage
import org.skia.foundation.SkImageInfo
import org.skia.foundation.SkPaint
import org.skia.foundation.SkSamplingOptions
import org.skia.math.SkISize

/**
 * Port of Skia's `gm/alpha_image.cpp::DEF_SIMPLE_GM(alpha_image, …, 256, 256)`.
 *
 * Builds a 96 × 96 [SkColorType.kAlpha_8] image whose triangle bottom-left
 * half is 0xFF and the top-right half is 0x0A (per `make_alpha_image`'s
 * `eraseARGB(10, 0, 0, 0)` + per-pixel `0xFF` fill below the diagonal).
 * The synthetic image is then drawn four times through a 2 × 2 grid :
 *
 *  - (16, 16)   — colour-filter + blur mask filter.
 *  - (144, 16)  — shader = solid cyan + blur mask filter (no colour filter).
 *  - (16, 144)  — colour-filter + blur mask filter (shader still set).
 *  - (144, 144) — colour-filter, no mask filter, no shader.
 *
 * **Iso-fidelity caveat (documented H1.5 gap)** : `drawImage` on an
 * `kAlpha_8` source in `:kanvas-skia` doesn't yet modulate the sampled
 * alpha by `paint.color` (or by a paint shader's sampled colour). The
 * cyan-shader cell (top-right) renders as grey instead of tinted cyan,
 * and the colour-filter cells lose their hue. Similarity vs the
 * upstream reference is bounded by this — we accept a partial-port
 * floor of ~20 %.
 *
 * `mandrill_128.png` is **not** used by this GM — the asset reference in
 * the H1-finish batch table reflects the H1.5 issue note rather than a
 * real dependency. The synthetic A8 image generated by [makeAlphaImage]
 * is self-contained.
 *
 * C++ original :
 * ```cpp
 * DEF_SIMPLE_GM(alpha_image, canvas, 256, 256) {
 *   auto image = make_alpha_image(96, 96).asImage();
 *   SkPaint paint;
 *   paint.setColorFilter(make_color_filter());
 *   paint.setMaskFilter(SkMaskFilter::MakeBlur(kNormal_SkBlurStyle, 10.0f));
 *   canvas->drawImage(image.get(), 16, 16, SkSamplingOptions(), &paint);
 *   paint.setColorFilter(nullptr);
 *   paint.setShader(SkShaders::Color(SK_ColorCYAN));
 *   canvas->drawImage(image.get(), 144, 16, SkSamplingOptions(), &paint);
 *   paint.setColorFilter(make_color_filter());
 *   canvas->drawImage(image.get(), 16, 144, SkSamplingOptions(), &paint);
 *   paint.setMaskFilter(nullptr);
 *   canvas->drawImage(image.get(), 144, 144, SkSamplingOptions(), &paint);
 * }
 * ```
 */
public class AlphaImageGM : GM() {

    override fun getName(): String = "alpha_image"

    override fun getISize(): SkISize = SkISize.Make(256, 256)

    override fun onDraw(canvas: SkCanvas?) {
        val c = canvas ?: return

        val image = makeAlphaImage(96, 96)
        val paint = SkPaint()

        // Cell 1 — (16, 16) : colour filter + 10-sigma normal blur.
        paint.colorFilter = makeColorFilter()
        paint.maskFilter = SkBlurMaskFilter.Make(SkBlurStyle.kNormal, 10.0f)
        c.drawImage(image, 16f, 16f, SkSamplingOptions.Default, paint)

        // Cell 2 — (144, 16) : no colour filter, cyan paint substitute for
        // `SkShaders::Color(SK_ColorCYAN)` (no constant-colour shader
        // factory in `:kanvas-skia` — set paint.color and clear shader).
        paint.colorFilter = null
        paint.shader = null
        paint.color = SK_ColorCYAN
        c.drawImage(image, 144f, 16f, SkSamplingOptions.Default, paint)

        // Cell 3 — (16, 144) : colour filter back, paint colour stays cyan
        // (matches upstream's "shader still set" semantic ; in our port the
        // cyan colour rides through paint.color instead).
        paint.colorFilter = makeColorFilter()
        c.drawImage(image, 16f, 144f, SkSamplingOptions.Default, paint)

        // Cell 4 — (144, 144) : no mask filter, paint colour + colour filter.
        paint.maskFilter = null
        c.drawImage(image, 144f, 144f, SkSamplingOptions.Default, paint)
    }

    /**
     * Mirrors upstream's `make_alpha_image(w, h)` :
     *  - alloc an `MakeA8(w, h)` bitmap,
     *  - `eraseARGB(10, 0, 0, 0)` — top-right triangle stays at alpha 10,
     *  - for `y in [0, h)` and `x in [y, w)` set the byte to 0xFF.
     *
     * The output is the asImage() snapshot.
     */
    private fun makeAlphaImage(w: Int, h: Int): SkImage {
        val bm = SkBitmap.allocPixels(SkImageInfo.MakeA8(w, h))
        // Fill with alpha 10 (= 0x0A). eraseColor on an A8 bitmap reads
        // the alpha byte (top 8 bits of SkColor) and broadcasts it.
        bm.eraseColor(0x0A000000)
        for (y in 0 until h) {
            for (x in y until w) {
                bm.pixelsA8[y * w + x] = 0xFF.toByte()
            }
        }
        return bm.asImage()
    }

    /**
     * Mirrors upstream's `make_color_filter()` — 4 × 5 matrix that keeps R
     * and G, then mixes B and A into the bottom two channels :
     * ```
     * 1 0 0   0   0
     * 0 1 0   0   0
     * 0 0 0.5 0.5 0
     * 0 0 0.5 0.5 0
     * ```
     */
    private fun makeColorFilter(): SkColorFilter {
        val matrix = floatArrayOf(
            1f, 0f, 0f, 0f, 0f,
            0f, 1f, 0f, 0f, 0f,
            0f, 0f, 0.5f, 0.5f, 0f,
            0f, 0f, 0.5f, 0.5f, 0f,
        )
        return SkColorFilters.Matrix(matrix)
    }
}
